#!/bin/sh

"exec" "clj" "-Sdeps"  '{:deps {clj-http {:mvn/version "3.10.0"} enlive {:mvn/version "1.1.6"}}}' "$0" "$@"

(ns kaunas-jug.example
  (:require [clj-http.client :as http]
            [net.cgrand.enlive-html :as html]))

(defn parse [body]
  (html/text body))

(defn fetch-past-events []
  (-> (http/get "http://kaunas-jug.lt/")
      :body
      (parse)))

(println fetch-past-events)
